Repository OCA/product-configurator, pull requests merged in 2021-06, with the labels that each got.

#28 [IMP] product_configurator_mrp(Config Sets Not Working Issue#20)
  product_configurator_mrp/data/menu_product.xml
  product_configurator_mrp/models/mrp.py
  product_configurator_mrp/models/product_config.py
  product_configurator_mrp/views/mrp_view.xml
Labels: bot is merging ⏳

#33 [FIX]product_configurator_mrp: reconfigure button visible in draft only
  product_configurator_mrp/views/mrp_view.xml
Labels: bot is merging ⏳

#12 14.0 mig website product configurator
  setup/website_product_configurator/odoo/addons/website_product_configurator
  setup/website_product_configurator/setup.py
  website_product_configurator/README.md
  website_product_configurator/__init__.py
  website_product_configurator/__manifest__.py
  website_product_configurator/controllers/__init__.py
  website_product_configurator/controllers/main.py
  website_product_configurator/data/config_form_templates.xml
  website_product_configurator/data/cron.xml
  website_product_configurator/data/ir_config_parameter_data.xml
  website_product_configurator/demo/product_template_demo.xml
  website_product_configurator/i18n/de.po
  website_product_configurator/i18n/website_product_configurator.pot
  website_product_configurator/models/__init__.py
  website_product_configurator/models/product_config.py
  website_product_configurator/models/res_config_settings.py
  website_product_configurator/models/sale_order.py
  website_product_configurator/security/configurator_security.xml
  website_product_configurator/static/description/cover.png
  website_product_configurator/static/description/icon.png
  website_product_configurator/static/src/css/config_form.css
  website_product_configurator/static/src/css/tooltip.css
  website_product_configurator/static/src/js/config_form.js
  website_product_configurator/static/src/js/website_config_tour.js
  website_product_configurator/static/src/js/website_sale.js
  website_product_configurator/static/src/scss/config_form.scss
  website_product_configurator/static/src/scss/tooltip.scss
  website_product_configurator/tests/__init__.py
  website_product_configurator/tests/test_product_config.py
  website_product_configurator/tests/test_res_config_settings.py
  website_product_configurator/tests/test_sale_order.py
  website_product_configurator/tests/test_website_product_config.py
  website_product_configurator/tests/test_website_product_configurator_values.py
  website_product_configurator/views/assets.xml
  website_product_configurator/views/product_view.xml
  website_product_configurator/views/res_config_settings_view.xml
  website_product_configurator/views/templates.xml
Labels: bot is merging ⏳

#38 [14.0][FIX] Isuue #34: Website Product Configurator error message
  website_product_configurator/data/config_form_templates.xml
Labels: approved, bot is merging ⏳

#31 14.0 mig product configurator purchase
  product_configurator_purchase/README.rst
  product_configurator_purchase/__init__.py
  product_configurator_purchase/__manifest__.py
  product_configurator_purchase/data/menu_product.xml
  product_configurator_purchase/demo/product_template.xml
  product_configurator_purchase/models/__init__.py
  product_configurator_purchase/models/purchase.py
  product_configurator_purchase/readme/DESCRIPTION.rst
  product_configurator_purchase/security/ir.model.access.csv
  product_configurator_purchase/static/description/icon.png
  product_configurator_purchase/static/description/index.html
  product_configurator_purchase/tests/__init__.py
  product_configurator_purchase/tests/test_purchase.py
  product_configurator_purchase/views/purchase_view.xml
  product_configurator_purchase/wizard/__init__.py
  product_configurator_purchase/wizard/product_configurator.py
  setup/product_configurator_purchase/odoo/addons/product_configurator_purchase
  setup/product_configurator_purchase/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#39 Add pcatinean as maintainer for all modules
  product_configurator/__manifest__.py
  product_configurator_mrp/__manifest__.py
  product_configurator_purchase/__manifest__.py
  product_configurator_sale/__manifest__.py
  product_configurator_sale_mrp/__manifest__.py
  website_product_configurator/__manifest__.py
Labels: bot is merging ⏳

#29 14.0 mig product_configurator_stock
  product_configurator_stock/README.rst
  product_configurator_stock/__init__.py
  product_configurator_stock/__manifest__.py
  product_configurator_stock/data/menu_product.xml
  product_configurator_stock/demo/product_template.xml
  product_configurator_stock/models/__init__.py
  product_configurator_stock/models/stock_move.py
  product_configurator_stock/models/stock_picking.py
  product_configurator_stock/readme/DESCRIPTION.rst
  product_configurator_stock/readme/USAGE.rst
  product_configurator_stock/security/ir.model.access.csv
  product_configurator_stock/static/description/icon.png
  product_configurator_stock/static/description/index.html
  product_configurator_stock/tests/__init__.py
  product_configurator_stock/tests/test_stock.py
  product_configurator_stock/views/product_view.xml
  product_configurator_stock/views/stock_move_view.xml
  product_configurator_stock/views/stock_picking_view.xml
  product_configurator_stock/wizard/__init__.py
  product_configurator_stock/wizard/product_configurator.py
  setup/product_configurator_stock/odoo/addons/product_configurator_stock
  setup/product_configurator_stock/setup.py
Labels: Migration, Needs review, approved, bot is merging ⏳, ready to merge

#32 14.0 mig website product configurator mrp
  setup/website_product_configurator_mrp/odoo/addons/website_product_configurator_mrp
  setup/website_product_configurator_mrp/setup.py
  website_product_configurator_mrp/README.rst
  website_product_configurator_mrp/__init__.py
  website_product_configurator_mrp/__manifest__.py
  website_product_configurator_mrp/controllers/__init__.py
  website_product_configurator_mrp/controllers/main.py
  website_product_configurator_mrp/i18n/de.po
  website_product_configurator_mrp/i18n/website_product_configurator_mrp.pot
  website_product_configurator_mrp/readme/DESCRIPTION.rst
  website_product_configurator_mrp/static/description/index.html
  website_product_configurator_mrp/static/src/js/website_sale.js
  website_product_configurator_mrp/views/assets.xml
  website_product_configurator_mrp/views/templates.xml
Labels: Migration, Needs review, approved, bot is merging ⏳, ready to merge

#35 [14.0] [FIX] product_configurator_sale_mrp (Error no attribute bom_id)
  product_configurator_sale_mrp/README.rst
  product_configurator_sale_mrp/readme/DESCRIPTION.rst
  product_configurator_sale_mrp/wizard/product_configurator.py
Labels: bot is merging ⏳
