Repository OCA/product-configurator, pull requests merged in 2021-05, with the labels that each got.

#8 [FIX] product_configurator: remove old readme file
  product_configurator/README.md
Labels: approved, bot is merging ⏳

#3 [14.0] [MIG] product_configurator_sale: Migrated the module in v14.
  product_configurator_sale/README.rst
  product_configurator_sale/__init__.py
  product_configurator_sale/__manifest__.py
  product_configurator_sale/data/menu_product.xml
  product_configurator_sale/demo/res_partner_demo.xml
  product_configurator_sale/models/__init__.py
  product_configurator_sale/models/sale.py
  product_configurator_sale/readme/DESCRIPTION.rst
  product_configurator_sale/security/ir.model.access.csv
  product_configurator_sale/static/description/icon.png
  product_configurator_sale/tests/__init__.py
  product_configurator_sale/tests/test_sale.py
  product_configurator_sale/views/sale_view.xml
  product_configurator_sale/wizard/__init__.py
  product_configurator_sale/wizard/product_configurator.py
  setup/product_configurator_sale/odoo/addons/product_configurator_sale
  setup/product_configurator_sale/setup.py
Labels: bot is merging ⏳

#11 14.0 [MIG] product configurator base
  product_configurator/README.md
  product_configurator/README.rst
  product_configurator/__manifest__.py
  product_configurator/data/menu_configurable_product.xml
  product_configurator/i18n/product_configurator.pot
  product_configurator/models/__init__.py
  product_configurator/models/ir_ui_view.py
  product_configurator/models/product.py
  product_configurator/models/product_config.py
  product_configurator/security/ir.model.access.csv
  product_configurator/static/js/form_widgets.js
  product_configurator/tests/test_wizard.py
  product_configurator/views/product_attribute_view.xml
  product_configurator/views/product_config_view.xml
  product_configurator/views/product_view.xml
  product_configurator/wizard/product_configurator.py
  product_configurator/wizard/product_configurator_view.xml
Labels: bot is merging ⏳

#6 [14.0] [MIG] product_configurator_mrp: Migrated the module in v14.
  product_configurator_mrp/README.rst
  product_configurator_mrp/__init__.py
  product_configurator_mrp/__manifest__.py
  product_configurator_mrp/data/menu_product.xml
  product_configurator_mrp/demo/product_template.xml
  product_configurator_mrp/i18n/de.po
  product_configurator_mrp/i18n/product_configurator_mrp.pot
  product_configurator_mrp/models/__init__.py
  product_configurator_mrp/models/mrp.py
  product_configurator_mrp/models/product_config.py
  product_configurator_mrp/readme/DESCRIPTION.rst
  product_configurator_mrp/security/configurator_security.xml
  product_configurator_mrp/security/ir.model.access.csv
  product_configurator_mrp/static/description/icon.png
  product_configurator_mrp/static/src/js/form_controller.js
  product_configurator_mrp/static/src/js/kanban_controller.js
  product_configurator_mrp/static/src/js/list_controller.js
  product_configurator_mrp/static/src/scss/mrp_config.scss
  product_configurator_mrp/static/src/xml/mrp_production_views.xml
  product_configurator_mrp/tests/__init__.py
  product_configurator_mrp/tests/test_mrp.py
  product_configurator_mrp/views/assets.xml
  product_configurator_mrp/views/mrp_view.xml
  product_configurator_mrp/wizard/__init__.py
  product_configurator_mrp/wizard/product_configurator_mrp.py
  setup/product_configurator_mrp/odoo/addons/product_configurator_mrp
  setup/product_configurator_mrp/setup.py
Labels: Migration, Needs review

#15 [FIX]remove stock from depends
  product_configurator/__manifest__.py
  product_configurator/views/product_view.xml
Labels: approved, bot is merging ⏳

#27 [FIX] product_configurator: missing variable initialization in product configurator wizard
  product_configurator/wizard/product_configurator.py
Labels: bot is merging ⏳

#24 [14.0][FIX] product_configurator: form_widget.js because it conflicted with the evaluation of the contexts in a form
  product_configurator/static/js/form_widgets.js
Labels: bot is merging ⏳
