Repository OCA/product-configurator, pull requests merged in 2022-03, with the labels that each got.

#62 [14.0][IMP]product_configurator_mrp_component
  product_configurator_mrp_component/models/mrp_bom.py
  product_configurator_mrp_component/views/mrp_bom.xml
Labels: bot is merging ⏳, approved

#61 [FIX] product_configurator
  product_configurator/models/product.py
Labels: bot is merging ⏳, approved, ready to merge

#63 [FIX] product_configurator_mrp_component: configurable component selection and variant creation
  product_configurator_mrp_component/models/mrp_bom.py
  product_configurator_mrp_component/models/product_config.py
Labels: bot is merging ⏳

#64 [IMP] website_product_configurator (Cron noupdate)
  website_product_configurator/data/cron.xml
Labels: bot is merging ⏳
