Repository OCA/product-configurator, pull requests merged in 2024-10, with the labels that each got.

#119 [FIX] product_configurator_sale: Price unit comes from the session
  product_configurator_sale/models/sale.py
  product_configurator_sale/tests/__init__.py
  product_configurator_sale/tests/test_sale_order_line.py
  product_configurator_sale/wizard/product_configurator.py
Labels: bot is merging ⏳

#132 [16.0] product_configurator: improve tests
  product_configurator/tests/__init__.py
  product_configurator/tests/common.py
  product_configurator/tests/test_product.py
  product_configurator/tests/test_product_config.py
  product_configurator/tests/test_wizard.py
Labels: bot is merging ⏳

#126 [IMP] product_configurator: Allow to restrict custom value
  product_configurator/README.rst
  product_configurator/models/product.py
  product_configurator/models/product_attribute.py
  product_configurator/models/product_config.py
  product_configurator/readme/CONTRIBUTORS.rst
  product_configurator/tests/__init__.py
  product_configurator/tests/test_configuration_rules.py
  product_configurator/views/product_config_view.xml
  product_configurator/wizard/product_configurator.py
Labels: bot is merging ⏳

#102 [MIG] product_configurator_mrp: Migration to 16.0
  product_configurator_mrp/README.rst
  product_configurator_mrp/__init__.py
  product_configurator_mrp/__manifest__.py
  product_configurator_mrp/data/menu_product.xml
  product_configurator_mrp/demo/product_template.xml
  product_configurator_mrp/i18n/de.po
  product_configurator_mrp/i18n/product_configurator_mrp.pot
  product_configurator_mrp/models/__init__.py
  product_configurator_mrp/models/mrp.py
  product_configurator_mrp/models/product_config.py
  product_configurator_mrp/readme/CONTRIBUTORS.rst
  product_configurator_mrp/readme/DESCRIPTION.rst
  product_configurator_mrp/security/configurator_security.xml
  product_configurator_mrp/security/ir.model.access.csv
  product_configurator_mrp/static/description/icon.png
  product_configurator_mrp/static/description/index.html
  product_configurator_mrp/static/src/js/form_controller.js
  product_configurator_mrp/static/src/js/kanban_controller.js
  product_configurator_mrp/static/src/js/list_controller.js
  product_configurator_mrp/static/src/scss/mrp_config.scss
  product_configurator_mrp/static/src/xml/mrp_production_views.xml
  product_configurator_mrp/tests/__init__.py
  product_configurator_mrp/tests/test_mrp.py
  product_configurator_mrp/views/mrp_view.xml
  product_configurator_mrp/wizard/__init__.py
  product_configurator_mrp/wizard/product_configurator_mrp.py
  setup/product_configurator_mrp/odoo/addons/product_configurator_mrp
  setup/product_configurator_mrp/setup.py
Labels: bot is merging ⏳, approved, migration, needs review

#133 [16.0][IMP] product_configurator: cleanup (pre-commit + reactivate tests)
  product_configurator/models/ir_ui_view.py
  product_configurator/models/product.py
  product_configurator/models/product_attribute.py
  product_configurator/models/product_config.py
  product_configurator/tests/__init__.py
  product_configurator/tests/common.py
  product_configurator/tests/test_configuration_rules.py
  product_configurator/tests/test_create.py
  product_configurator/tests/test_product.py
  product_configurator/tests/test_product_attribute.py
  product_configurator/tests/test_product_config.py
  product_configurator/tests/test_wizard.py
  product_configurator/wizard/product_configurator.py
Labels: enhancement, bot is merging ⏳, needs review
